import {
  AlertTriangle,
  ArrowRight,
  BookOpen,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CircleDashed,
  Command,
  CreditCard,
  File,
  FileText,
  Film,
  HelpCircle,
  ImageIcon,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogOut,
  Moon,
  MoreVertical,
  Music,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  Users,
  X,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  logout: LogOut,
  twitter: Twitter,
  check: Check,
  dashboard: LayoutDashboard,
  file: File,
  fileText: FileText,
  CircleDashed: CircleDashed,
  CircleHelp: CircleHelp,
  // Iconos para géneros artísticos
  Music: Music,
  Users: Users,
  Film: Film,
  Image: ImageIcon,
  BookOpen: BookOpen,
}
